11_week11/04_assessment/TheGroanZone/Models/Joke.cs
using System.ComponentModel.DataAnnotations;

namespace TheGroanZone.Models;

public class Joke
{
    [Key]
    public int Id { get; set; }
    public string Setup { get; set; } = string.Empty;
    public string Punchline { get; set; } = string.Empty;
    // Foreign key
    public int UserId { get; set; }

    // navigation
    public User? User { get; set; }
    public List<Rating> Ratings { get; set; } = [];

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

}

11_week11/04_assessment/TheGroanZone/ViewModels/EditJokeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TheGroanZone.ViewModels;

public class EditJokeViewModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Setup must be at least 2 characters")]
    [MinLength(2, ErrorMessage = "Setup must be at least 2 characters")]
    public string Setup { get; set; } = string.Empty;

    [Required(ErrorMessage = "Punchline must be at least 2 characters")]
    [MinLength(2, ErrorMessage = "Punchline must be at least 2 characters")]
    public string Punchline { get; set; } = string.Empty;

    public int UserId { get; set; }

}

11_week11/04_assessment/TheGroanZone/ViewModels/JokeViewModel.cs
namespace TheGroanZone.ViewModels;

public class JokeViewModel
{
    public int Id { get; set; }
    public string Setup { get; set; } = string.Empty;
    public string Punchline { get; set; } = string.Empty;
    public string Username { get; set; } = string.Empty; // Holds the Username for the user that submitted the joke
    public string AvgRating { get; set; } = string.Empty;
    public int TotalRatings { get; set; }
    public List<string> UsersThatHaveRated { get; set; } = [];
    public int? UserRating { get; set; } // Specific rating a user has given. Used to determine the rating a user gave to a joke
    public int UserId { get; set; }
    public String CreatedAt { get; set; } = string.Empty;

}

11_week11/04_assessment/TheGroanZone/Controllers/JokeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheGroanZone.Models;
using TheGroanZone.ViewModels;

namespace TheGroanZone.Controllers;

[Route("jokes")]
public class JokeController : Controller
{
    private readonly ApplicationContext _context;
    private readonly ILogger<JokeController> _logger;

    private const string SessionUserId = "userId";

    public JokeController(ApplicationContext context, ILogger<JokeController> logger)
    {
        _context = context;
        _logger = logger;
    }

    [HttpGet("")]
    public async Task<IActionResult> AllJokes()
    {
        var userId = HttpContext.Session.GetInt32(SessionUserId);


        // checks if user is logged in. If not, returns unauthorized view
        // checks if user is logged in. If not, returns unauthorized view
        if (userId is not int uid)
        {
            return Unauthorized();
        }

        var jokes = await _context
        .Jokes
        .AsNoTracking()
        .Select(j => new JokeViewModel
        {
            Id = j.Id,
            Setup = j.Setup,
            Punchline = j.Punchline,
            UserId = j.UserId,
            Username = j.User!.Username,
            CreatedAt = j.CreatedAt.ToString("MMM d, yyyy"),
            AvgRating = j.Ratings.Average(r => r.UserRating).ToString("F1"),
        }).ToListAsync();

        var vm = new JokeIndexViewModel
        {
            Jokes = jokes
        };

        return View(vm);
    }

    [HttpGet("new")]
    public IActionResult JokeForm()
    {
        var userId = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userId is not int uid)
        {
            return Unauthorized();
        }

        var vm = new JokeFormViewModel();

        return View(vm);
    }

    [ValidateAntiForgeryToken]
    [HttpPost("new")]
    public async Task<IActionResult> AddJoke(JokeFormViewModel vm)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }
        if (!ModelState.IsValid)
        {
            return View(nameof(JokeForm), vm);
        }

        // create new Joke
        var newJoke = new Joke
        {
            Setup = vm.Setup,
            Punchline = vm.Punchline,
            UserId = uid
        };

        await _context.Jokes.AddAsync(newJoke);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AllJokes));
    }

    [HttpGet("{jokeId}/edit")]
    public async Task<IActionResult> EditJoke(int jokeId)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        var vm = await _context.Jokes.AsNoTracking().Where(j => j.Id == jokeId).Select(j => new EditJokeViewModel
        {
            Id = j.Id,
            Setup = j.Setup,
            Punchline = j.Punchline,
            UserId = j.UserId,
        }).FirstOrDefaultAsync();

        if (uid != vm!.UserId)
        {
            // return Forbid(); // forbid keeps returning a 500 error so I replaced it with a manual 403 instead
            _logger.LogWarning("Warning: Unauthorized attempt to delete joke {jokeId} by unauthenticated user.", jokeId);
            return StatusCode(403);
        }

        return View(vm);
    }

    [ValidateAntiForgeryToken]
    [HttpPost("{jokeId}/edit")]
    public async Task<IActionResult> UpdateJoke(int jokeId, EditJokeViewModel viewModel)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        if (!ModelState.IsValid)
        {
            return View(nameof(EditJoke), viewModel);
        }

        var joke = await _context.Jokes.FindAsync(jokeId);

        if (joke == null)
        {
            return NotFound();
        }

        joke.Setup = viewModel.Setup;
        joke.Punchline = viewModel.Punchline;
        joke.UpdatedAt = DateTime.Now;

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(JokeDetails), new { jokeId = joke.Id });
    }

    [HttpGet("{jokeId}/delete")]
    public async Task<IActionResult> DeleteJoke(int jokeId)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        var vm = await _context.Jokes.AsNoTracking().Where(j => j.Id == jokeId).Select(j => new JokeViewModel
        {
            Id = j.Id,
            // Setup = j.Setup,
            UserId = j.UserId
        }).FirstOrDefaultAsync();

        if (uid != vm!.UserId)
        {
            // return Forbid(); // forbid keeps returning a 500 error
            return StatusCode(403);
        }

        return View(vm);
    }

    [ValidateAntiForgeryToken]
    [HttpPost("{jokeId}/delete")]
    public async Task<IActionResult> RemoveJoke(int jokeId)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        var joke = await _context.Jokes.FindAsync(jokeId);

        if (joke == null)
        {
            return NotFound();
        }

        _context.Remove(joke);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AllJokes));
    }

    // --------------------Ratings--------------------------------

    [ValidateAntiForgeryToken]
    [HttpPost("{jokeId}/rate")]
    public async Task<IActionResult> AddRating(int jokeId, int rating)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        // only allows ratings from 1 to 4, anything outside of that redirects to the same joke page
        if (!(rating >= 1 && rating <= 4))
        {
            return RedirectToAction(nameof(JokeDetails), new { jokeId = jokeId });
        }

        var maybeRated = await _context
        .Ratings
        .Where(rating => rating.UserId == uid && rating.JokeId == jokeId)
        .FirstOrDefaultAsync();

        if (maybeRated is null)
        {

            var newRating = new Rating
            {
                UserId = uid,
                JokeId = jokeId,
                UserRating = rating,
            };

            await _context.AddAsync(newRating);
            await _context.SaveChangesAsync();
        }
        else
        {
            var existingRating = await _context.Ratings.FindAsync(maybeRated.Id);

            existingRating!.UserRating = rating;
            existingRating.UpdatedAt = DateTime.UtcNow;
            await _context.SaveChangesAsync();

        }

        return RedirectToAction(nameof(JokeDetails), new { jokeId = jokeId });
    }

    [HttpGet("{jokeId}")]
    public async Task<IActionResult> JokeDetails(int jokeId)
    {
        var userid = HttpContext.Session.GetInt32(SessionUserId);

        // checks if user is logged in. If not, returns unauthorized view
        if (userid is not int uid)
        {
            return Unauthorized();
        }

        var vm = await _context.Jokes.AsNoTracking().Where(j => j.Id == jokeId).Select(j => new JokeViewModel
        {
            Id = j.Id,
            Setup = j.Setup,
            Punchline = j.Punchline,
            UserId = j.UserId,
            Username = j.User!.Username,
            TotalRatings = j.Ratings.Where(r => r.JokeId == jokeId).ToList().Count,
            // Left this dereference warning because I need the value to be null whenever the user 
            // has not rated the joke. The check for null is done in the JokeDetails View, so no issues arise.
            UserRating = j.Ratings
                        .FirstOrDefault(r => r.JokeId == jokeId && r.UserId == uid)
                        .UserRating,
            AvgRating = j.Ratings.Average(j => j.UserRating).ToString("F1"),
            UsersThatHaveRated = j.Ratings.OrderByDescending(r => r.CreatedAt).Select(r => r.User!.Username).Take(5).ToList(), // Holds the newest 5 users that have rated the joke

        }).FirstOrDefaultAsync();

        // check if jokewas not found
        if (vm is null)
        {
            return NotFound();
        }

        return View(vm);
    }

}

11_week11/04_assessment/TheGroanZone/Views/Joke/AllJokes.cshtml
@model JokeIndexViewModel

@{
    ViewData["Title"] = "Jokes";
    var jokes = Model.Jokes;
    var sessionId = Context.Session.GetInt32("userId");
}

@if(jokes.Count < 1){
    <h1>No jokes added yet</h1>
}
else{
    <h1>All Dad Jokes</h1>


    <div class="container">
         @for(int i = 0; i < jokes.Count; i = i + 2){
        <div class="row gap-3 d-flex mb-3">
            <div class="col">
                <div class="card shadow h-100 ">
                    <div class="card-body justify-content-between d-flex flex-column">
                        <div class="mb-3">
                            <p>@jokes[i].Setup</p>
                            <p>@jokes[i].Punchline</p>
                        </div>
                        <div class="text-muted ">
                            <p class="justify-content-end d-flex">Dad: @jokes[i].Username</p>
                            <p class="justify-content-end d-flex">Added @jokes[i].CreatedAt</p>
                        </div>
                    </div>

                    <div class="card-footer text-muted justify-content-between d-flex">
                        <div>@(jokes[i].AvgRating == null ? "No" : jokes[i].AvgRating) groans</div>
                        <a href="jokes/@jokes[i].Id">view</a>
                    </div>
                </div>
            </div>
            @if(i+1 < jokes.Count){
            <div class="col">
                <div class="card shadow h-100 ">
                    <div class="card-body justify-content-between d-flex flex-column">
                        <div class="mb-3">
                            <p>@jokes[i+1].Setup</p>
                            <p>@jokes[i+1].Punchline</p>
                        </div>
                        <div class="text-muted ">
                            <p class="justify-content-end d-flex">Dad: @jokes[i+1].Username</p>
                            <p class="justify-content-end d-flex">Added @jokes[i+1].CreatedAt</p>
                        </div>
                    </div>

                    <div class="card-footer text-muted justify-content-between d-flex">
                        <div>@(jokes[i+1].AvgRating == null ? "No" : jokes[i+1].AvgRating) groans</div>
                        <a href="jokes/@jokes[i+1].Id">view</a>
                    </div>
                </div>
            </div>
            }
            else{
                <div class="col">
                </div>
            }
            @if(i+2 >= jokes.Count){
                break;
            }
        </div>
        }
    </div> 
}

11_week11/04_assessment/TheGroanZone/Views/Joke/DeleteJoke.cshtml
@model JokeViewModel

@{
    ViewData["Title"] = "Delete Joke";

    var joke = Model;
}

<h1>Delete Joke</h1>

<div class="card shadow">
    <div class="card-body">
        <form asp-action="RemoveJoke" asp-controller="Joke" method="post" asp-route-jokeId="@joke.Id">
            <p>Are you sure you want to delete joke from the database?</p>
            <p>(This action cannot be reversed)</p>
            <div class="text-start d-flex justify-content-between">
                <a href="/jokes/@joke.Id" class="btn btn-primary">Go back</a>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
    </div>
</div>

11_week11/04_assessment/TheGroanZone/Views/Joke/EditJoke.cshtml
@model EditJokeViewModel

@{
    ViewData["Title"] = "Edit Joke";
    var joke = Model;
}

<h1>Add a Joke</h1>

<div class="card shadow">
    <div class="card-body">
        <form asp-action="UpdateJoke" asp-controller="Joke" method="post" asp-route-jokeId="@joke.Id">
            <div class="mb-3">
                <label asp-for="Setup" class="form-label">Setup:</label>
                <textarea asp-for="Setup" class="form-control"></textarea>
                <span asp-validation-for="Setup" class="form-text text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Punchline" class="form-label">Punchline:</label>
                <textarea asp-for="Punchline" class="form-control"></textarea>
                <span asp-validation-for="Punchline" class="form-text text-danger"></span>
            </div>
            <div class="text-start d-flex justify-content-between">
                <a href="/jokes/@joke.Id" class="btn btn-primary">Go back</a>
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

11_week11/04_assessment/TheGroanZone/Views/Joke/JokeDetails.cshtml
@model JokeViewModel

@{
    ViewData["Title"] = "Joke Details";
    var joke = Model;
}

<section class="d-flex gap-3">
    <div class="" style="flex: 2">
        <div class="card shadow">
            <div class="card-body">
                <h1>Joke Details</h1>
                <div class="mb-3">
                    <p><strong>Setup: </strong>@joke.Setup</p>
                </div>
                <div>
                    <p><strong>Punchline: </strong>@joke.Punchline</p>
                </div>
            </div>
            @if(joke.UserId == Context.Session.GetInt32("userId")){
            <div class="card-footer text-muted justify-content-end gap-2 d-flex">
                <a href="/jokes/@joke.Id/edit">edit</a>
                <a href="/jokes/@joke.Id/delete">delete</a>
            </div>
            }
        </div>
    </div>
    <div class="d-flex gap-3 flex-column" style="flex: 1">
        <div class="card shadow p-3" style="flex: 1">
            <h2>Stats</h2>
            @if(joke.TotalRatings == 0){
                <p><strong>No ratings found.</strong> Why not give this joke it's first rating down below?</p>
            }
            else{
            <ul class="list-unstyled">
                <li><strong>Ratings:</strong> @joke.TotalRatings</li>
                <li><strong>Average rating:</strong> @joke.AvgRating</li>
                <li>
                    Rated By:
                    <ul>
                        @foreach(var username in joke.UsersThatHaveRated){
                            <li>@username</li>
                        }    
                    </ul>
                </li>
            </ul>
            }
        </div>
        <div class="card shadow p-3" style="flex: 1">
            <h2>Rate this joke:</h2>
            <form asp-action="AddRating" asp-controller="Joke" method="post" asp-route-jokeId="@joke.Id" class="mb-3">
                <div class="mb-3">
                    <select name="rating" id="rating">
                        <option disabled selected="@(joke.UserRating == null)" value="0"> -- Select groan amount -- </option>
                        @for(int i = 1; i <= 4; i++){
                            <option value="@i" selected="@(joke.UserRating == i)">@i</option>
                        }
                    </select>
                    @* <span asp-validation-for="Setup" class="form-text text-danger"></span> *@
                </div>
                <div class="text-end">
                    <button type="submit" class="btn btn-primary">Rate</button>
                </div>
            </form>
        </div>
    </div>
</section>

11_week11/04_assessment/TheGroanZone/Views/Joke/JokeForm.cshtml
@model JokeFormViewModel

@{
    ViewData["Title"] = "Add a Joke";
}

<h1>Add a Dad Joke</h1>

<div class="card shadow">
    <div class="card-body">
        <form asp-action="AddJoke" asp-controller="Joke" method="post">
            <div class="mb-3">
                <label asp-for="Setup" class="form-label">Setup:</label>
                <textarea asp-for="Setup" class="form-control"></textarea>
                <span asp-validation-for="Setup" class="form-text text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Punchline" class="form-label">Punchline:</label>
                <textarea asp-for="Punchline" class="form-control"></textarea>
                <span asp-validation-for="Punchline" class="form-text text-danger"></span>
            </div>
            <div class="text-end">
                <button type="submit" class="btn btn-primary">Add Joke</button>
            </div>
        </form>
    </div>
</div>